[project]
name = "databasus-ansible-collection"
version = "1.2.2"
description = "Ansible collection to manage Databasus resources via REST API"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "ansible>=14.1.0",
    "ansible-doc-extractor>=0.1.11",
    "argparse>=1.4.0",
    "jinja2>=3.1.0",
]

[project.urls]
Homepage = "https://github.com/zeqk/databasus-ansible-collection"
Repository = "https://github.com/zeqk/databasus-ansible-collection"
Issues = "https://github.com/zeqk/databasus-ansible-collection/issues"
